Browser=chrome
url=https://opensource-demo.orangehrmlive.com/
username=Admin
password=admin123

firstName=Vaibhav
middleName=Rao
lastName=K
vacancy=Software Engineer
email=vrk@gmail.com
mobile=9876544210
filePath=C:/Users/ASUS/Downloads/Vaibhav-K-Resume.pdf
